id: error-intake
namespace: main
inputs:
  - id: error_event
    type: JSON
    required: true

tasks:
  - id: log_error
    type: io.kestra.plugin.core.log.Log
    message: "Error event: {{ inputs.error_event }}"
    level: INFO




{
  "error_event": {
    "service": "ui-test",
    "error_type": "TestError",
    "message": "Ran from UI"
  }
}

